### ISSUE TITLE
bigMoji command does not send emoji

### ISSUE THREAD

**Issue by silvia-odwyer** [Strum355/2Bot-Discord-Bot#20]
2Bot's command checking functionality is case sensitive, so that if I type `bigMoji`, 2Bot doesn't recognise that command, while it does recognise `bigmoji`.
`!owo bigMoji :eyes:` does nothing so far, while `!owo bigmoji :eyes:` does indeed send the eyes.

**Comment by Strum355** [comment]
clarification: command checking itself is case *in*sensitive. the bigmoji command is a special case, for some reason this one isnt being treated like that :thinking:

**Comment by silvia-odwyer** [comment]
Ah, so it's only case sensitive for that special case then. I saw in your msgEmoji.go code on Line `62` that you're getting the user's typed emoji only if the first word of msglist is `bigmoji`. I dunno if ORring that with a bigMoji would help, so that Line 62 would read `if msglist[0] == "bigmoji" || msglist[0] == "bigMoji"`. I dunno if that would fix it though, cos maybe msgEmoji.go isn't getting called in the first place. 

```go
if msglist[0] == "bigmoji" {
		if len(msglist) < 2 {
			return
		}
		emoji = msglist[1]
	} else {
		emoji = msglist[0]
}```

**Comment by Strum355** [comment]
Welp that seems about right :stuck_out_tongue_closed_eyes: if you want you can submit a quick PR for that
