### ISSUE TITLE
.travis.yml is configured to build with Go 1.8.X, and master

### ISSUE THREAD

**Issue by jmfgdev** [Strum355/2Bot-Discord-Bot#3]
Travis has Go 1.9 available, I tried it, along with master, like you do, with the following builds:

  https://travis-ci.org/jmfgdev/coin-toss.go/builds/276593410  
  https://travis-ci.org/jmfgdev/moreutils.go/builds/276593616
  https://travis-ci.org/jmfgdev/amidabot.go/builds/276593775
  https://travis-ci.org/jmfgdev/go-rng/builds/276593812

They all worked! So I think it's time to update the .travis.yml

**Comment by Strum355** [comment]
Closed, check PR comment : )
